# Generated by Django 4.2.1 on 2024-05-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_comment_media_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dude_date',
            new_name='due_date',
        ),
    ]
